version: '3'

volumes:
  cache:
    driver: local
  db-data-news:
    driver: local
  db-data-auth:
    driver: local

services:

  news:
    build: ./news
    container_name: news
    depends_on:
      - db_news
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_news:5432/clevertec_news
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    expose:
      - '8001'
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://news:8001/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3


  comment:
    build: ./comment
    container_name: comment
    depends_on:
      - news
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_news:5432/clevertec_news
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    expose:
      - '8002'
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://comment:8002/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3


  auth:
    build: ./auth
    container_name: auth
    depends_on:
      - db_auth
      - comment
    env_file:
      - .env.properties
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_auth:5432/clevertec_auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    expose:
      - '8003'
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://auth:8003/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - auth
    ports:
      - '8000:8000'

  db_news:
    image: postgres:15.1-alpine
    container_name: db_news
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=clevertec_news
    volumes:
      - ./db-init:/docker-entrypoint-initdbNews.d
      - db-data-news:/var/lib/postgresql/data

  db_auth:
    image: postgres:15.1-alpine
    container_name: db_auth
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=clevertec_auth
    volumes:
      - ./db-init:/docker-entrypoint-initdbAuth.d
      - db-data-auth:/var/lib/postgresql/data

  redis:
    image: redis:7.2.3-alpine
    restart: always
    container_name: redis
    ports:
      - '6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass cGFzc3dvcnRvcmVkaXM=
    volumes:
      - cache:/data