version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.news
    container_name: news
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/clevertec_news
    #      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/clevertec_news?currentSchema=news
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - '8001:8001'

  db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=clevertec_news
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d