server:
  port: 8000

spring:
  cloud:
    openfeign:
      client:
        config:
          news-service:
            url: http://news:8001/news
            connect-timeout: 3000
            read-timeout: 5000
          comment-service:
            url: http://comment:8002/comments
            connect-timeout: 3000
            read-timeout: 5000
          auth-service:
            url: http://auth:8003/auth
            connect-timeout: 3000
            read-timeout: 5000
          admin-service:
            url: http://auth:8003/admin
            connect-timeout: 3000
            read-timeout: 5000

resilience4j:
  retry:
    instances:
      news-service-retry:
        max-attempts: 3
        wait-duration: 3s
        retry-exceptions:
          - feign.FeignException.BadGateway
      comment-service-retry:
        max-attempts: 3
        wait-duration: 3s
        retry-exceptions:
          - feign.FeignException.BadGateway
      auth-service-retry:
        max-attempts: 3
        wait-duration: 3s
        retry-exceptions:
          - feign.FeignException.BadGateway
      admin-service-retry:
        max-attempts: 3
        wait-duration: 3s
        retry-exceptions:
          - feign.FeignException.BadGateway
  circuitbreaker:
    instances:
      news-service-breaker:
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 75
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        max-wait-duration-in-half-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
      comment-service-breaker:
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 75
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        max-wait-duration-in-half-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
      auth-service-breaker:
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 75
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        max-wait-duration-in-half-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
      admin-service-breaker:
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 75
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        max-wait-duration-in-half-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
