spring:
  profiles:
    active: prod

gateway:
  openapi:
    dev-url: http://localhost:8000

springdoc:
  swagger-ui:
    path: /documentation
    try-it-out-enabled: true
  api-docs:
    path: /api-doc
  packages-to-scan: by.clevertec.gateway.controller

jwt:
  secret: qwerty232425ndjdysjrndhhsjjeesppsuurvxnhhfdkksdurnnsjj22234isknfnnfl8845jjdjdcscacassascbb353fdcd
  lifetime: 10m
