#FROM openjdk:17-jdk-slim
#COPY --from=build /target/*.jar dto-box.jar
#
#FROM gradle:6.9.1-jdk11 AS build
#WORKDIR /
#COPY /src /src
#RUN gradle build

#FROM openjdk:17-jdk-slim
#FROM gradle:6.9.1-jdk11 AS build
#WORKDIR /app
#
#COPY . .
#
#RUN ./gradlew build