spring:
  profiles:
    active: dev, lfu-lru
    default: dev
#  datasource:
#    tomcat:
#      driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/clevertec_news
##    url: jdbc:postgresql://localhost:5434/clevertec_news
#    username: postgres
#    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
comment:
  openapi:
    dev-url: http://localhost:8002
springdoc:
  swagger-ui:
    path: /documentation
    try-it-out-enabled: true
  api-docs:
    path: /api-doc
  packages-to-scan: by.clevertec.comment.controller
cache:
  algorithm: lfu
  max-collection-size: 100
server:
  port: 8002
