spring:

  profiles:
    active: dev, lfu-lru
    default: dev

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

news:
  openapi:
    dev-url: http://localhost:8001
springdoc:
  swagger-ui:
    path: /documentation
    try-it-out-enabled: true
  api-docs:
    path: /api-doc
  packages-to-scan: by.clevertec.news.controller

server:
  port: 8001
